### ISSUE TITLE
Equals sign is able to crash Urchin

### ISSUE THREAD

**Issue by Spakman** [Spakman/urchin#21]
This gives an exception:

```
$ git co -b =
Urchin exited.

NoMethodError: undefined method `<<' for nil:NilClass
/home/mark/src/urchin/lib/parser.rb:195:in `arg_with_equals'
/home/mark/src/urchin/lib/parser.rb:281:in `words'
/home/mark/src/urchin/lib/parser.rb:142:in `parse_command'
/home/mark/src/urchin/lib/parser.rb:60:in `parse_job'
/home/mark/src/urchin/lib/parser.rb:28:in `jobs_from'
/home/mark/src/urchin/lib/shell.rb:59:in `parse_and_run'
/home/mark/src/urchin/lib/shell.rb:35:in `run'
/home/mark/src/urchin/bin/urchin:41:in `<main>'
```

**Comment by Spakman** [comment]
A more realistic example:

    chmod og= /boom
